### PR TITLE
A new node which provide link to the image

### PR DESCRIPTION
**Pull request by Diddlik**

### CODE REVIEW

**Comment by ihrigb** [comment]
@Diddlik thanks for the contribution. I am not quite sure if a node of this kind is a good idea. I'd like to more understand why this would be useful. What is your use case?

**Comment by Diddlik** [comment]
The idea is, if someone rings or possibly gives a movement, then it triggers the image node and you can notify e.g. via Telegram. Best option would be not to send the link, but the image itself (possibly binary) or allow to save it.

**Comment by ihrigb** [comment]
Ok, got it. Then why not have a node that loads the image itself? Shame that node red does not support encoding, so it would be necessary to encode it in Base64 or so:
```
{
  "payload": {
    "image": "<base64 image data>",
    "timestamp": "<timestamp"
  }
}
```
No necessary to add the timestamp though. But maybe we should add information about the image type? We should also check the image size to avoid too much memory being used.

**Comment by ihrigb** [comment]
Wait stupid me... The payload *can* actually contain buffers. So this would be the best option!

```
{
  "payload": {
    "data": <Buffer>,
    <further fields, if required or profitable>
  }
}
```

**Comment by Diddlik** [comment]
At the moment this is my solution:
grafik

**Comment by ihrigb** [comment]
The next release will contain an additional node for this!

**Comment by ihrigb** [comment]
Available now since `v1.2.0`

**Pull request closed without merging**
